### ISSUE TITLE
telegrambot已经成功操作，请问怎么备份到onedrive云盘？

### ISSUE THREAD

**Issue by Jacky-Bruse** [gaowanliang/DownloadBot#10]
现在在telegram已经正常，请问怎么设置上传到onedrive云盘？我是在vps上进行操作的，直接下载的linux版本，想要上传onedrive还需要下载source code进行配置吗？还是其它操作？请指教。谢谢

**Comment by gaowanliang** [comment]
请自行探索，稳定版时会给出具体教程

**请注意，当前版本仍非稳定版，只处于基本能用的状态，不保证您的正常使用**

**Comment by Jacky-Bruse** [comment]
> 请自行探索，稳定版时会给出具体教程
> 
> **请注意，当前版本仍非稳定版，只处于基本能用的状态，不保证您的正常使用**

好的，很有意思
