### ISSUE TITLE
panic: stat : no such file or directory

### ISSUE THREAD

**Issue by EdisonJwa** [gaowanliang/DownloadBot#11]
系统环境 Debian 10 x64
在配置完成 `config.json` 文件后，运行 DownloadBot 二进制文件时报错

<details>
<summary>报错信息如下</summary>

```2021/01/24 13:21:09 12346
2021/01/24 13:21:09 stat : no such file or directory
panic: stat : no such file or directory
goroutine 1 [running]:
log.Panic(0xc000093e80, 0x1, 0x1)
        D:/program_app/go/src/log/log.go:351 +0xac
main.dropErr(...)
        D:/program_data/go/DownloadBot/main.go:14
main.locLan(0xc0000a867a, 0x5)
        D:/program_data/go/DownloadBot/utils.go:69 +0xba
main.init.0()
        D:/program_data/go/DownloadBot/main.go:26 +0x181
```
</details>

**Comment by gaowanliang** [comment]
目前为测试阶段，没有对`downloadFolder`和`moveFolder`进行处理，目前必须在这两个参数后填写有效的地址，一直要改一直都忘了，将在下一个版本解决。

**请注意，当前版本仍非稳定版，只处于基本能用的状态，不保证您的正常使用**

**Comment by EdisonJwa** [comment]
好的 那么请问如果不需要移动是否只需要将 `downloadFolder `和 `moveFolder `填写同样内容即可呢

**Comment by gaowanliang** [comment]
目前的话随意指定一个**实际存在**的文件夹即可

**请注意，当前版本仍非稳定版，只处于基本能用的状态，不保证您的正常使用**

**Comment by EdisonJwa** [comment]
抱歉 现在出现了新的错误
`panic: message "configCompleted" not found in language "zh"`

<details>
<summary>Details</summary>

```2021/01/24 13:33:15 12346
panic: message "configCompleted" not found in language "zh"

goroutine 1 [running]:
github.com/nicksnyder/go-i18n/v2/i18n.(*Localizer).MustLocalize(0xc0002b0080, 0xc00008de80, 0xc00013a7c8, 0x16)
        D:/program_data/go/DownloadBot/vendor/github.com/nicksnyder/go-i18n/v2/i18n/localizer.go:211 +0x79
main.locText(0xc00008df18, 0x1, 0x1, 0x0, 0x0)
        D:/program_data/go/DownloadBot/utils.go:157 +0xd5
main.init.0()
        D:/program_data/go/DownloadBot/main.go:27 +0x1be```

</details>

**Comment by gaowanliang** [comment]
请根据[这里](https://github.com/gaowanliang/DownloadBot/blob/main/README_zh-CN.md#%E7%9B%AE%E5%89%8D%E6%94%AF%E6%8C%81%E7%9A%84%E8%AF%AD%E8%A8%80%E5%8F%8A%E8%AF%AD%E8%A8%80%E6%A0%87%E7%AD%BE)所指示的语言代码重新填写`language`参数

**请注意，当前版本仍非稳定版，只处于基本能用的状态，不保证您的正常使用**

**Comment by EdisonJwa** [comment]
抱歉 我已经根据文档进行过了更改，报错信息也没有改变

```{
  "aria2-server": "HIDDEN",
  "aria2-key": "HIDDEN",
  "bot-key": "HIDDEN",
  "user-id": "HIDDEN",
  "max-index": 10,
  "sign": "Main Aria2",
  "language": "en", // 测试过语言为中文（各种）及英文的状态下均报同样的错误
  "downloadFolder": "HIDDEN",
  "moveFolder":"HIDDEN"
}```

**Comment by gaowanliang** [comment]
暂时不知道是什么问题导致的，你可以自行去[这里](https://github.com/gaowanliang/DownloadBot/tree/main/i18n)下载对应的语言包，放入软件生成的`i18n`文件夹中，详细原因再待查明。

**请注意，当前版本仍非稳定版，只处于基本能用的状态，不保证您的正常使用**

**Comment by EdisonJwa** [comment]
@gaowanliang 测试后发现 运行后程序自动创建的目录 当前(非root)用户无读取权限 导致报错
