### ISSUE TITLE
多用户机器人使用

### ISSUE THREAD

**Issue by qcgzxw** [gaowanliang/DownloadBot#13]
希望可以增加多用户使用
- config.json user-id 允许多个用户
- config.json group-id 允许群组使用

**Comment by gaowanliang** [comment]
多用户将在下个版本支持
群组内使用短期内不会专门支持，但会处于设计列表内，将会在合适的时机内支持（因为由于除了tg，还牵扯到其他chat平台的适配）

**请注意，本程序仍处于beta阶段，仅供体验，不能保证您的正常使用**
