### ISSUE TITLE
上傳Google drive報錯

### ISSUE THREAD

**Issue by LSOIVNE** [gaowanliang/DownloadBot#16]
λ go run drive.go struct.go Aria2.go main.go Telegram.go utils.go
2021/02/19 21:45:17 配置信息加载完成！
2021/02/19 21:45:17 与 ws://127.0.0.1:6800/jsonrpc 连接中
2021/02/19 21:45:17 Aria2 websocket连接已建立！Aria2版本：1.35.0
2021/02/19 21:45:17 已登入授权账户 xxxxxxx_DownloadBot
2021/02/19 21:45:34 Aria2Data
2021/02/19 21:45:34 Unable to create folder: Post "https://www.googleapis.com/drive/v3/files?alt=json&prettyPrint=false": oauth2: token expired and refresh token is not set
panic: Unable to create folder: Post "https://www.googleapis.com/drive/v3/files?alt=json&prettyPrint=false": oauth2: token expired and refresh token is not set

goroutine 50 [running]:
log.Panicf(0xa48e7b, 0x1b, 0xc000435dc8, 0x1, 0x1)
        C:/Program Files/Go/src/log/log.go:361 +0xc7
googledrive.GetAllFile(0xc00001ae61, 0x9, 0x0, 0x0, 0x0, 0xc000272080, 0x602fc0fe, 0xc0004084c8, 0x18, 0xc0004ae108, ...)
        C:/DownloadBot/vendor/googledrive/gdUpload.go:124 +0x39e
googledrive.Upload(0xc0005383c0, 0x30, 0xc00001ae61, 0x9, 0xa67278, 0xa67280)
        C:/DownloadBot/vendor/googledrive/gdUpload.go:240 +0x46e
created by main.uploadDFToGoogleDrive
        C:/DownloadBot/drive.go:61 +0x14b
exit status 2

還有config.json的downloadFolder設置不了，它會下載到Aria2設置/默認的位置。留空的話啓動會報錯。

![image](https://user-images.githubusercontent.com/30148130/108513360-775fee00-72fd-11eb-8827-0e41bc90a604.png)

**Comment by gaowanliang** [comment]
Google drive的API目前有刷新問題，我還在研究中。最近比較忙，沒時間來寫這個程式，最多來回復一下，我原本想把Google drive做好後再上傳一個Releases的，您可以稍事等待，或者使用rclone掛載gd再通過程式來複製到掛載的資料夾中。

downloadFolder就是要和aria2的默認下載檔案夾相同，因為通過aria2的API在某些系統上無法返回設置的下載位址的絕對路徑，所以才要求填寫的。如果是為了設置aria2的下載位址實際上是多此一舉的，明明可以在aria2的設置選項中填寫，幹嘛要再在這個程式裡設置一次。

PS：如果您是慣用繁體的，可以直接使用`zh-TW`語言包（雖然是通過office機翻，包括現在😅.....
