### ISSUE TITLE
支持下docker吧

### ISSUE THREAD

**Issue by 547555909** [gaowanliang/DownloadBot#2]
如题，不会用go运行

**Comment by gaowanliang** [comment]
请根据您的系统直接下载[releases](https://github.com/gaowanliang/DownloadBot/releases)中的压缩包，解压后运行，根据readme中的操作进行配置config.json文件，等到稳定版后，会出一键脚本等工具，*但是docker在很长的时间内都不会支持*

**请注意，当前版本仍非稳定版，只处于基本能用的状态，不保证您的正常使用**

**Comment by 547555909** [comment]
Linux的压缩包解压后怎么在vps里运行啊？

**Comment by 547555909** [comment]
> 请根据您的系统直接下载[releases](https://github.com/gaowanliang/DownloadBot/releases)中的压缩包，解压后运行，根据readme中的操作进行配置config.json文件，等到稳定版后，会出一键脚本等工具，_但是docker在很长的时间内都不会支持_
> 
> **请注意，当前版本仍非稳定版，只处于基本能用的状态，不保证您的正常使用**

输入什么命令？
