### ISSUE TITLE
麻烦添加下bot连接aria的重连

### ISSUE THREAD

**Issue by justcopy** [gaowanliang/DownloadBot#3]
aria2重启后，bot不会自动重连。

**Comment by gaowanliang** [comment]
好的，会在后续版本中加入aria2实时状态检测以及重连等功能

**请注意，当前版本仍非稳定版，只处于基本能用的状态，不保证您的正常使用**

**Comment by gaowanliang** [comment]
已在[955f4ebe](https://github.com/gaowanliang/DownloadBot/commit/10a604f9e39f99d728a4f82e0e164a7e955f4ebe)提交中实现，将在下个release中整合进程序。
