### ISSUE TITLE
这个是什么原因呢，亲亲

### ISSUE THREAD

**Issue by zkysimon** [gaowanliang/DownloadBot#4]
![image](https://user-images.githubusercontent.com/61656204/103136674-531cd200-46fd-11eb-8d88-60be8b85222f.png)
![image](https://user-images.githubusercontent.com/61656204/103136702-81021680-46fd-11eb-8cb9-013047d53168.png)

**Comment by gaowanliang** [comment]
你种子内的文件太多了，没有办法以列表的形式展现，由于目前为测试版，仅提供最原始的一些功能，对于这些问题的优化，将会在稳定版中解决

**请注意，当前版本仍非稳定版，只处于基本能用的状态，不保证您的正常使用**

**Comment by zkysimon** [comment]
> 正

好的哦，期待你的更新
