### ISSUE TITLE
绑定od，发送跳转的地址后，程序会退出

### ISSUE THREAD

**Issue by aria001** [gaowanliang/DownloadBot#6]
![image](https://user-images.githubusercontent.com/17241830/103287662-0c411c00-4a1e-11eb-9761-ff4e5d71f587.png)
运行环境为ubuntu18
看样子是一些路径写死成windows下的路径了？

**Comment by gaowanliang** [comment]
这个路径不会影响运行，具体提示的路径和我编译的机器有关，这样你们报错方便我查找错误，这个错误很有可能是你跳转的地址填写的不对，里面一定要包含`code=`这个关键字，这里我没有做具体的错误处理，后续会改进。
