### ISSUE TITLE
运行错误

### ISSUE THREAD

**Issue by Seeger0216** [gaowanliang/DownloadBot#7]
当我配置好的config.json后，运行./DownloadBot，提示这些：
`````
root@i-e5e2f29565ddd8a1:~# ./DownloadBot 
2020/12/30 06:56:40 12346
置信氥 载實06:56:40 
`````
我没法判断这是什么错误，我应该怎么办？另外，在提示这些之后，我的tg机器人仍然是没有任何反应的。

**Comment by gaowanliang** [comment]
请贴上您的`config.json`，隐私处请进行忽略

**请注意，当前版本仍非稳定版，只处于基本能用的状态，不保证您的正常使用**

**Comment by Jacky-Bruse** [comment]
请教大佬，
{
  "aria2-server": "ws://127.0.0.1:5800/jsonrpc",
  "aria2-key": "xxxxxxxx",
  "bot-key": "123456789:xxxxxxxxx",
  "user-id": "123456789",
  "max-index": 10,
  "sign": "Main Aria2",
  "language": "zh-CN",
  "downloadFolder": "C:/aria2/Aria2Data",
  "moveFolder":"C:/aria2/GoogleDrive"
}

  "aria2-key": "xxxxxxxx",这个怎么获取？
