### ISSUE TITLE
一次启动就只能下一个磁力

### ISSUE THREAD

**Issue by cloudfly23** [gaowanliang/DownloadBot#8]
一次启动就只能下一个磁力
再添加磁力就自动暂停，但是又不出现文件选择框，然后就卡死了，其他命令也失效了
![image](https://i0.wp.com/user-images.githubusercontent.com/42934604/103643615-f8526880-4f8f-11eb-826a-ff7abdb11d21.png)

**Comment by gaowanliang** [comment]
请粘贴后台报错数据

**请注意，当前版本仍非稳定版，只处于基本能用的状态，不保证您的正常使用**

**Comment by cloudfly23** [comment]
后台没报错，只显示
```
2021/01/05 07:02:56 BT 任务 [{4cc369bf85e8f715}] 已完成！
2021/01/05 07:02:56 [{9a6be3cce17c246a}] 任务开始下载！
2021/01/05 07:02:56 [{4cc369bf85e8f715}] 任务已完成！
2021/01/05 07:03:05 [{9a6be3cce17c246a}] 任务暂停！
2021/01/05 07:03:22 [{9a6be3cce17c246a}] 任务开始下载！
2021/01/05 07:03:58 [{90509563cebf6902}] 任务开始下载！
2021/01/05 07:04:08 [{90509563cebf6902}] 任务暂停！
2021/01/05 07:04:21 [{90509563cebf6902}] 任务开始下载！
2021/01/05 07:04:43 [{90509563cebf6902}] 任务暂停！
```
但是就是第二个磁力无法显示选择文件的步骤
![image](https://i0.wp.com/user-images.githubusercontent.com/42934604/103644594-972b9480-4f91-11eb-865c-2e470d10408b.png)

**Comment by Jacky-Bruse** [comment]
我也有这样的情况，最近几天还在纠结，突然想到有人说过这个问题

**Comment by gaowanliang** [comment]
> 我也有这样的情况，最近几天还在纠结，突然想到有人说过这个问题

应该是出在提交.torrent文件的情况下会有这个问题，我有时间测试一下。最近要考研了，只能忙里偷闲的时候才能更新，一直想更都没时间😂。

**Comment by Jacky-Bruse** [comment]
> > 我也有这样的情况，最近几天还在纠结，突然想到有人说过这个问题
> 
> 应该是出在提交.torrent文件的情况下会有这个问题，我有时间测试一下。最近要考研了，只能忙里偷闲的时候才能更新，一直想更都没时间😂。

不急，只是反馈一下，祝愿大佬考研成功，加油，谢谢提供这么好的工具

**Comment by luyiwind** [comment]
> > > 我也有这样的情况，最近几天还在纠结，突然想到有人说过这个问题
> > 
> > 
> > 应该是出在提交.torrent文件的情况下会有这个问题，我有时间测试一下。最近要考研了，只能忙里偷闲的时候才能更新，一直想更都没时间😂。
> 
> 不急，只是反馈一下，祝愿大佬考研成功，加油，谢谢提供这么好的工具

Telegram.go中将下边的break改成continue可fix

			if b[1] == "Start" {
				setTMDownloadFilesAndStart(gid, lastFilesInfo)
				bot.Send(tgBotApi.NewDeleteMessage(myID, MessageID))
				break
			}

**Comment by gaowanliang** [comment]
> > > > 我也有这样的情况，最近几天还在纠结，突然想到有人说过这个问题
> > > 
> > > 
> > > 应该是出在提交.torrent文件的情况下会有这个问题，我有时间测试一下。最近要考研了，只能忙里偷闲的时候才能更新，一直想更都没时间😂。
> > 
> > 
> > 不急，只是反馈一下，祝愿大佬考研成功，加油，谢谢提供这么好的工具
> 
> Telegram.go中将下边的break改成continue可fix
> 
> ```
> 		if b[1] == "Start" {
> 			setTMDownloadFilesAndStart(gid, lastFilesInfo)
> 			bot.Send(tgBotApi.NewDeleteMessage(myID, MessageID))
> 			break
> 		}
> ```

确实是这里的问题，十分感谢
