### ISSUE TITLE
遇到的一个问题，ssh要一直连

### ISSUE THREAD

**Issue by Jacky-Bruse** [gaowanliang/DownloadBot#9]
ssh连接，并且输入一次./DownloadBot，之后才会有消息提醒，一旦退出ssh，再点“正在下载”，点击按钮机器人没有任何提示，直到再次ssh连接，然后执行./DownloadBot才正常，退出又没有了，如此反复，请问大佬知道怎么解决？

**Comment by gaowanliang** [comment]
目前没做守护进程，请使用screen这个程序进行后台运行，具体使用方法请自行查找。

**请注意，当前版本仍非稳定版，只处于基本能用的状态，不保证您的正常使用**

**Comment by Jacky-Bruse** [comment]
> 目前没做守护进程，请使用screen这个程序进行后台运行，具体使用方法请自行查找。
> 
> **请注意，当前版本仍非稳定版，只处于基本能用的状态，不保证您的正常使用**

感谢大佬的指导，我发现运行 ：./DownloadBot &
之后也可以正常了，很好用，期待大佬的后续更新
